export const GET_ALL_BLOG_REQUEST = 'GET_ALL_BLOG_REQUEST'; 
export const GET_ALL_BLOG_SUCCESS = 'GET_ALL_BLOG_SUCCESS';
export const GET_ALL_BLOG_FAIL = 'GET_ALL_BLOG_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


export const CREATE_BLOG_REQUEST = 'CREATE_BLOG_REQUEST';
export const CREATE_BLOG_SUCCESS = 'CREATE_BLOG_SUCCESS';
export const CREATE_BLOG_FAIL = 'CREATE_BLOG_FAIL';


export const GET_BLOG_DETAILS_REQUEST = 'GET_BLOG_DETAILS_REQUEST'; 
export const GET_BLOG_DETAILS_SUCCESS = 'GET_BLOG_DETAILS_SUCCESS';
export const GET_BLOG_DETAILS_FAIL = 'GET_BLOG_DETAILS_FAIL';