export const GET_GALARY_REQUEST = 'GET_GALARY_REQUEST';
export const GET_GALARY_SUCCESS = 'GET_GALARY_SUCCESS';
export const GET_GALARY_FAIL = 'GET_GALARY_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
